inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 7
