language: ruby
sudo: false
rvm: 2.5.1
cache:
  bundler: true
  directories:
  - $HOME/.rvm
env:
  global:
  - COVERAGE=1
  matrix:
  - INTEGRATION_SPECS=0
  - INTEGRATION_SPECS=1
services:
- redis-server
before_install: gem install bundler
before_script: source .example.env
notifications:
  email: false
