#!/usr/bin/env ruby
# frozen_string_literal: true

libdir = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require 'pupcycler'
require 'pry'
Pry.prompt = Pry::SIMPLE_PROMPT
Pry.start
