#!/usr/bin/env bash
set -o errexit

main() {
  if [[ ! "${GOPATH_BIN}" ]]; then
    GOPATH_BIN="$(go env GOPATH | awk -F: '{ print $1 }')/bin"
  fi

  local top
  top="$(git rev-parse --show-toplevel)"

	"${GOPATH_BIN}/gometalinter" --disable-all \
		-E deadcode \
		-E goconst \
		-E gofmt \
		-E goimports \
		-E golint \
		-E vet \
		--deadline=1m --vendor "${top}" "${top}"/cmd/*/
	"${GOPATH_BIN}/checkmake" "${top}/Makefile"
}

main "${@}"
